cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #303219
selection_background  #c8c9a6
url_color             #c6cd5b

color0   #131313
color1   #e34a74
color2   #90d66e
color3   #dbb47b
color4   #90961e
color5   #959955
color6   #c6cd5b
color7   #abb2bf
color8   #5c6370
color9   #e05f86
color10  #a3e086
color11  #e8c797
color12  #d7d98b
color13  #85792e
color14  #737e3a
color15  #ffffff
