return {}
-- return {
-- 	{
-- 		"lukas-reineke/indent-blankline.nvim",
-- 		main = "ibl",
-- 		config = function()
-- 			local highlight = {
-- 				"RainbowRed",
-- 				"RainbowYellow",
-- 				"RainbowBlue",
-- 				"RainbowGreen",
-- 				"RainbowMagenta",
-- 				"RainbowCyan",
-- 				"RainbowWhite",
-- 			}
-- 			local hooks = require("ibl.hooks")
--
-- 			-- Create highlight groups
-- 			hooks.register(hooks.type.HIGHLIGHT_SETUP, function()
-- 				vim.api.nvim_set_hl(0, "RainbowRed", { fg = "#f7768e" })
-- 				vim.api.nvim_set_hl(0, "RainbowYellow", { fg = "#e0af68" })
-- 				vim.api.nvim_set_hl(0, "RainbowBlue", { fg = "#7aa2f7" })
-- 				vim.api.nvim_set_hl(0, "RainbowGreen", { fg = "#9ece6a" })
-- 				vim.api.nvim_set_hl(0, "RainbowMagenta", { fg = "#bb9af7" })
-- 				vim.api.nvim_set_hl(0, "RainbowCyan", { fg = "#7dcfff" })
-- 				vim.api.nvim_set_hl(0, "RainbowWhite", { fg = "#a9b1d6" })
-- 			end)
-- 			require("ibl").setup({
-- 				indent = { highlight = highlight },
-- 			})
-- 		end,
-- 	},
-- }
