[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]
live_config_reload = true

[env]
TERM = "alacritty"

[window]
opacity = 0.8
startup_mode = "Windowed"
decorations_theme_variant = "Dark"
dynamic_padding = true
dynamic_title = false

[window.padding]
x=2
y=0

[window.dimensions]
columns = 100
lines = 25

[font]
size = 14

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "ExtraBold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"

[cursor.style]
shape = "Beam"
blinking = "Always"

[[keyboard.bindings]]
key = "Q"
mods = "Control|Shift"
action = "Quit"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3