[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#464a00'

[colors.cursor]
text = '#131313'
cursor = '#c6cd5b'

[colors.normal]
black   = '#131313'
red     = '#e34a74'
green   = '#90d66e'
yellow  = '#dbb47b'
blue    = '#90961e'
magenta = '#959955'
cyan    = '#c6cd5b'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f86'
green   = '#a3e086'
yellow  = '#e8c797'
blue    = '#d7d98b'
magenta = '#85792e'
cyan    = '#737e3a'
white   = '#ffffff'
